export const USE_CASES = ['RIDE', 'FLIGHT', 'HOTEL', 'MERCHANT', 'TRANSFER', 'ACADEMY', 'VIIZE'];

export const SOURCE_RAILS = [
  'PAWAPAY',
  'ORANGE_DIRECT',
  'MTN_DIRECT',
  'CAMPOST',
  'INTERAC',
  'STRIPE',
  'APPLE_PAY',
  'MASTERCARD',
  'SEPA',
  'SWIFT'
];

export const DESTINATION_RAILS = [
  'PAWAPAY_PAYOUT',
  'ORANGE_PAYOUT',
  'MTN_PAYOUT',
  'CAMPOST_PAYOUT',
  'BANK_SETTLEMENT',
  'CARD_SETTLEMENT',
  'MERCHANT_BALANCE'
];
