FROM node:20-bullseye

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
RUN npx prisma generate || true
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "dev"]
